[package]
name = "novade-core"
version = "0.1.0"
edition = "2021"

[dependencies]
thiserror = "1.0"
uuid = { version = "1.0", features = ["v4", "serde"] }
chrono = { version = "0.4", features = ["serde"] }
