[package]
name = "novade"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# Smithay for compositor
# GTK4 for shell
# tracing for logging
# other potential dependencies
```
