[package]
name = "novade-domain"
version = "0.1.0"
edition = "2021"
description = "Domain layer for the NovaDE desktop environment"
authors = ["NovaDE Team"]
license = "MIT"
repository = "https://github.com/novade/novade"
rust-version = "1.87.0"

[dependencies]
novade-core = { path = "../novade-core" }
serde = { version = "1.0.219", features = ["derive"] }
uuid = { version = "1.3.3", features = ["v4", "serde"] }
chrono = { version = "0.4.24", features = ["serde"] }
async-trait = "0.1.68"
thiserror = "1.0.40"
tracing = "0.1.37"
once_cell = "1.17.1"
tokio = { version = "1.28.0", features = ["full"] }

[dev-dependencies]
# Add any development-specific dependencies here, e.g., for testing
# For example, if you need a specific version of a crate for tests:
# criterion = "0.3"
