[package]
name = "novade-domain"
version = "0.1.0"
edition = "2021"

[dependencies]
novade-core = { path = "../novade-core" }
async-trait = "0.1.68"
serde = { version = "1.0", features = ["derive"] }
tokio = { version = "1", features = ["full"] }
