[package]
name = "novade-domain"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# Placeholder for novade-core, adjust path as necessary
novade-core = { path = "../novade-core" } # Assuming novade-core is a local dependency

thiserror = "1.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
uuid = { version = "1.6", features = ["v4", "serde"] }
chrono = { version = "0.4", features = ["serde"] }
async-trait = "0.1"
tokio = { version = "1", features = ["sync"] }
tracing = "0.1"

[dev-dependencies]
# Add any development-specific dependencies here, e.g., for testing
# For example, if you need a specific version of a crate for tests:
# criterion = "0.3"
