[package]
name = "vivox_domain"
version = "0.1.0"
edition = "2021"

[dependencies]
uuid = { version = "1.7.0", features = ["v4", "serde"] }
serde = { version = "1.0", features = ["derive"] }
thiserror = "1.0.58"
chrono = { version = "0.4.31", features = ["serde"] }
async-trait = "0.1.77"
