[package]
name = "nova_compositor"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
smithay = "0.3"
wayland-server = "0.29"
tracing = "0.1"
tracing-subscriber = "0.3"
