[package]
name = "novade-system"
version = "0.1.0"
edition = "2021"

[dependencies]
async-trait = "0.1" # Ensure this is present

[dev-dependencies]
# Add any development dependencies here, e.g., for testing
# tokio = { version = "1", features = ["rt-multi-thread", "macros"] } # For testing async code
# tracing-subscriber = { version = "0.3", features = ["env-filter"] } # For logging in tests
