[package]
name = "novade-system"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
smithay = { version = "0.10.0", features = ["backend_drm", "backend_egl", "renderer_gl", "wayland_frontend", "desktop"] }
calloop = "0.12.0"
wayland-server = "0.30.0"
wayland-protocols = { version = "0.30.0", features = ["server", "unstable"] } # Assuming 'unstable' is the correct feature for 0.30.0
thiserror = "1.0"
uuid = { version = "1.0", features = ["v4", "serde"] }
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }

# Graphics / Renderer dependencies
glow = "0.13"
khronos-egl = "6.0.0" # For EGL context management
# libloading is often a transitive dependency of khronos-egl for dynamic loading of EGL symbols
# but can be added explicitly if specific version is needed or direct use is planned.

# novade-core = { path = "../novade-core" } # Assuming these are local sibling crates
# novade-domain = { path = "../novade-domain" } # Adjust paths as necessary
