[package]
name = "novade-system"
version = "0.1.0"
edition = "2021"

[dependencies]
novade-core = { path = "../novade-core" }
novade-domain = { path = "../novade-domain" }
async-trait = "0.1.68"
tokio = { version = "1", features = ["full"] }
wayland-server = "0.31.0"
wayland-protocols = "0.31.0"
smithay = "0.6.0"
zbus = "3"
novade-compositor-core = { path = "../novade-compositor-core" }
ash = { version = "0.37" } # Ensure relevant features if ash itself provides them, though ash-window is typical
ash-window = "0.10"
gpu-allocator = { version = "0.22", features = ["ash"] }
raw-window-handle = "0.5"
