[package]
name = "novade_vulkan_renderer"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
vulkano = { version = "0.34.0", features = ["wayland"] }
log = "0.4.20"
smithay = { version = "0.18.0", features = ["renderer_gl", "renderer_vulkan"] }
gtk4 = "0.8.1"
env_logger = "0.10"
